<%@ Page Language="C#" AutoEventWireup="True" CodeBehind="Default.aspx.cs" Inherits="ASPXZipIt.WebForm1" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head id="Head1" runat="server">
    <title>ASPXZipIt-Backup-Web Content</title>
    <link href="styles/StyleSheet.css" rel="stylesheet" type="text/css" />
    <style type="text/css">
        .JaggedCorners
        {
            border: 1px solid black;
            -moz-border-radius: 25px 10px / 10px 25px;
            border-radius: 25px 10px / 10px 25px;
        }
        .Corners
        {
            border: 1px solid black;
            -moz-border-radius: 15px;
            border-radius: 15px;
        }
        .InterestingCorners
        {
            border: 1px solid black;
            -moz-border-radius: 1em 4em 1em 4em;
            border-radius: 1em 4em 1em 4em;
        }
        .Shadow
        {
            -moz-box-shadow: -5px -5px 5px #888;
            -webkit-box-shadow: -5px -5px 5px #888;
            box-shadow: -5px -5px 5px #888;
        }
        .container
        {
            width: 280px;
            border: 1px solid black;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }
        .container_wide
        {
            width: 330px;
            border: 1px solid black;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <center>
        <ul class="tabs group">
            <li class="active"><a href="#" onfocus="this.blur();">Files</a></li>
            <li><a href="zipit-db.aspx" onfocus="this.blur();">Databases</a></li>
            <li><a href="zipit-logs.aspx" onfocus="this.blur();">Logs</a></li>
        </ul>
    </center>
    <div class="wrapper">
        <asp:ScriptManager ID="MainScriptManager" runat="server" />
        <center>
            <div class="head">
                ASPXZipit Backup Utility</div>
            <h2>
                Available File Backups</h2>
        </center>
        <center>
            <em>
                <br />
                <br />
                <asp:GridView ID="availablebackups_gridview" OnRowDeleting="availablebackups_gridview_RowDeleting"
                    AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" BorderWidth="0"
                    BorderColor="#EEEEEE" runat="server">
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                </asp:GridView>
            </em>
        </center>
        <br />
        <asp:Label runat="server" ID="lblInfo" ForeColor="Red" Text="" />
        <br />
        <asp:Label runat="server" ID="lblInfo2" ForeColor="Red" Text="" />
        <br />
        <br />
        <center>
            <div>
                <asp:Button CssClass="button" ID="btnLongRuningTask" runat="server" Text="Zip It"
                    OnClick="BackupWebSiteContent_Click" Width="150px" />
                <br />
                <br />
            </div>
            <font size="1em">ASPXZipit Backup provided by <a href="https://github.com/onesandzeros415/ASPXZipIt"
                target="_blank">Matthew Costello</a></font>
        </center>
    </div>
    </form>
</body>
</html>
