<%@ Page Title="" Language="C#" MasterPageFile="~/aspxzipit/Site.Master" AutoEventWireup="True" CodeBehind="Default.aspx.cs" Inherits="ASPXZipIt.zipit_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="PageTitle" runat="server">
    ASPX Zipit - Backup Files
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="BodyHeader" runat="server">
    Available File Backups
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="Body" runat="server">
    <center>
    <asp:GridView ID="availablebackups_gridview" OnRowDeleting="availablebackups_gridview_RowDeleting"
        AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" BorderWidth="0"
        BorderColor="#EEEEEE" runat="server">
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
    </asp:GridView>
    <br />
    <asp:Label runat="server" ID="lblInfo" ForeColor="Red" Text="" />
    <br />
    <asp:Label runat="server" ID="lblInfo2" ForeColor="Red" Text="" />
    <br />
    <br />
    <div>
        <asp:Button CssClass="button" ID="btnLongRuningTask" runat="server" Text="Zip It"
            OnClick="BackupWebSiteContent_Click" Width="150px" />
        <br />
        <br />
    </div>
    </center>
</asp:Content>
