<%@ Page Title="" Language="C#" MasterPageFile="~/aspxzipit/Site.Master" AutoEventWireup="True" CodeBehind="zipit-db.aspx.cs" Inherits="ASPXZipIt.zipit_DB" %>

<asp:Content ID="Content1" ContentPlaceHolderID="PageTitle" runat="server">
    ASPX Zipit - Databases
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="BodyHeader" runat="server">
    Available Database Backups
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="Body" runat="server">
    <center>
    <asp:GridView ID="availablebackups_gridview" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" BorderWidth="0"
        BorderColor="#EEEEEE" runat="server">
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
    </asp:GridView>
    <br />
    <table>
        <tr>
            <td>Enter Hostname:
            </td>
            <td>
                <asp:TextBox runat="server" Height="25px" Width="215px" ID="Hostname" />
                <asp:RequiredFieldValidator ID="HostNameRequired" runat="server" ControlToValidate="Hostname"
                    ErrorMessage="HostName is required." ToolTip="HostName is required." ValidationGroup="BackupMssqlValidationGroup">*</asp:RequiredFieldValidator>
            </td>
        </tr>
        <tr>
            <td>Enter Database Name:
            </td>
            <td>
                <asp:TextBox runat="server" Height="25px" Width="215px" ID="Dbname" />
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="Dbname"
                    ErrorMessage="DBName is required." ToolTip="DBName is required." ValidationGroup="BackupMssqlValidationGroup">*</asp:RequiredFieldValidator>
            </td>
        </tr>
        <tr>
            <td>Enter Username:
            </td>
            <td>
                <asp:TextBox runat="server" Height="25px" Width="215px" ID="UsernameDB" />
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="UsernameDB"
                    ErrorMessage="UserName is required." ToolTip="UserName is required." ValidationGroup="BackupMssqlValidationGroup">*</asp:RequiredFieldValidator>
            </td>
        </tr>
        <tr>
            <td>Enter Password:
            </td>
            <td>
                <asp:TextBox runat="server" Height="25px" Width="215px" ID="Password" TextMode="Password" />
                <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="Password"
                    ErrorMessage="Password is required." ToolTip="Password is required." ValidationGroup="BackupMssqlValidationGroup">*</asp:RequiredFieldValidator>
            </td>
        </tr>
        <tr>
            <td>Path To Save Backup:
            </td>
            <td>
                <asp:TextBox runat="server" Height="25px" Width="215px" ID="FileBackuplocation" />
                <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="HostName"
                    ErrorMessage="Filelocation is required." ToolTip="Filelocatoin is required."
                    ValidationGroup="BackupMssqlValidationGroup">*</asp:RequiredFieldValidator>
            </td>
        </tr>
    </table>
    <br />
    <asp:Label runat="server" ID="lblInfo" ForeColor="Red" Text="" />
    <br />
    <asp:Label runat="server" ID="lblInfo2" ForeColor="Red" Text="" />
    <br />
    <br />
    <div>
        <asp:Button CssClass="button" ValidationGroup="BackupMssqlValidationGroup" ID="btnLongRuningTask"
            runat="server" Text="Zip It" OnClick="BackUpMssql_Click" Width="150px" />
        <asp:Button CssClass="button" ValidationGroup="BackupMssqlValidationGroup" ID="btnAddStoredProcedure"
            runat="server" Text="Install Stored Procedure" OnClick="btnAddStoredProcedure_Click"
            Width="150px" />
        <br />
        <br />
        <asp:Button CssClass="button" ValidationGroup="BackupMssqlValidationGroup" ID="btnShrinkLog"
            runat="server" Text="Shrink Log File" OnClick="btnShrinkLogFile_Click"
            Width="150px" />
        <br />
        <br />
    </div>
    </center>
</asp:Content>
